server:
  port: 9091
#  MySQL连接配置信息（以下仅简单配置，更多设置可自行查看）
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    #  连接地址（解决UTF-8中文乱码问题 + 时区校正）
    #  rewriteBatchedStatements=true 开启批处理模式）
    url: jdbc:mysql://192.168.0.170:3306/elco_edge_plcagent?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    #  用户名
    username: root
    #  密码
    password: toor
    #  连接驱动名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: Hikari
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 500000
      max-lifetime: 1800000
      connection-timeout: 300000
      validationTimeout: 300000
      connection-test-query: SELECT 1

# 批处理条数
consumer:
  db-consumer:
    consumerCount: 100
  status-consumer:
    consumerCount: 20

# 模式  test：测试模式 (默认|缺省)；prod：生产模式
mode:
  # 连接器模式
  connector-mode: test
  # 下发报文模式
  send-mode: test

# 超时处理警告-超时时间设定，毫秒数(Long)
warn-time: 3000

agent:
  code: "edge-agent"
  description: ""
  group-code: "test-group"
  protocol: "OpcUa"
  max-connections: 300
  uptime: 5000
